version: "3.7"
services:
  api:
    container_name: WALLET-API
    image: 
      github.com/atkinsonbg/go-gmux-proper-unit-testing/api:latest
    environment:
      DBHOST: wallet-api-db
      DBNAME: wallet-api-db
      DBUSER: postgres
    ports:
      - 80:80
  database:
    container_name: wallet-api-db
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: wallet-api-db
      volumes:
        - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432